### ISSUE TITLE
job was terminated when reading null p-values in trans QTL permutation analysis

### ISSUE THREAD

**Issue by mahoko** [qtltools/qtltools#25] opened 2020-09-02 08:00 UTC
HI all,

I'm  trying to analyze trans QTL using QTLtools version 1.2.
When runnning  approximate permutation analyses to adjust nominal  p-value, I got  an error "terminate called after throwing an instance of 'std::invalid_argument' what(): stof" .  The  job stopped at the step "Reading null p-values in [ my best.txt.gz]".
Could you please give some advice how to solve this problem?

**COMMAND**
QTLtools trans --vcf /data01/VCF/GRCh38_chr22.vcf.gz \
      --bed exp.bed.gz \                                                                                                          
      --adjust trans.best.txt.gz --normal --threshold 0.1 --out trans.adjust

**MESSAGE**
[32mQTLtools[0m
  * Authors : Olivier DELANEAU / Halit ONGEN / Emmanouil DERMITZAKIS
  * Contact : olivier.delaneau@gmail.com / halit.ongen@unige.ch / Emmanouil.Dermitzakis@unige.ch
  * Webpage : https://qtltools.github.io/qtltools/
  * Version : 1.2
  * Date    : 02/09/2020 - 15:57:51
  * Citation: A complete tool set for molecular QTL discovery and analysis, https://doi.org/10.1038/ncomms15452

[32mMAPPING QTL IN TRANS[0m
  * TASK: Test and adjust p-values using [trans.best.txt.gz]
  * Cis-window size is 5000000 bp
  * #bins = 1000
  * threshold = 0.1

Initialize random number generator
  * Built-in seed is 15112011
  * First Integer = 30554
  * First Double = 0.0126695

Read sample list from [/data01/VCF/GRCh38_chr22.vcf.gz]
  * #samples = 373

Checking sample list in [exp.bed.gz]
  * #samples = 373

Reading phenotype data in [exp.bed.gz] from line 0 to 0
  * 373 samples included
  * 293 phenotypes included

Normal transform phenotypes

Reading null p-values in [trans.best.txt.gz]

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stof

**Comment by halitongen** [comment] 2020-09-02 08:04
Can you try using v1.3.1 to check if the issue is resolved in the newest version?

**Comment by mahoko** [comment] 2020-09-03 02:33
I tried v1.3.1 and got no error! I don't have root  privileges on the server, it took a little time to install it. Hope we can get binaries for the new version. Anyway, thanks for fixing bugs!

**Closed** 2020-09-03 07:06 UTC
